"use client";
import { FormEvent, useEffect, useState } from "react";
import { LoaderCircle, PackagePlus } from "lucide-react";
import type { CreateIncomingInspectionLotInput, IncomingInspectionLevel, IncomingInspectionMethod, IncomingInspectionMethodPlan, IncomingInspectionType, IncomingLotResponsible } from "../types";
type Props = { responsiblePms: IncomingLotResponsible[]; loadingPms?: boolean; saving?: boolean; onSubmit: (input: CreateIncomingInspectionLotInput) => Promise<void>; onCancel: () => void };
export const METHOD_OPTIONS: Array<{ value: IncomingInspectionMethod; label: string }> = [{value:"documentary",label:"Documental"},{value:"visual",label:"Visual"},{value:"dimensional",label:"Dimensional"},{value:"functional",label:"Funcional"}];
const LEVELS: IncomingInspectionLevel[]=["I","II","III","S1","S2","S3","S4"];
const emptyPlan=(method:IncomingInspectionMethod):IncomingInspectionMethodPlan=>({method,isFullInspection:false,inspectedQuantity:0,inspectionType:"normal",inspectionLevel:"II",aql:"",allowedRejectedQuantity:0});
export default function IncomingLotForm({responsiblePms,loadingPms=false,saving=false,onSubmit,onCancel}:Props){
 const [lotName,setLotName]=useState(""); const [totalLotQuantity,setTotalLotQuantity]=useState(""); const [selectedMethods,setSelectedMethods]=useState<IncomingInspectionMethod[]>(["visual"]); const [responsiblePmEmail,setResponsiblePmEmail]=useState(""); const [formError,setFormError]=useState("");
 const [plans,setPlans]=useState<Record<IncomingInspectionMethod,IncomingInspectionMethodPlan>>(()=>Object.fromEntries(METHOD_OPTIONS.map(({value})=>[value,emptyPlan(value)])) as Record<IncomingInspectionMethod,IncomingInspectionMethodPlan>);
 useEffect(()=>{if(responsiblePms.length===1)setResponsiblePmEmail(responsiblePms[0].email)},[responsiblePms]);
 const update=<K extends keyof IncomingInspectionMethodPlan>(method:IncomingInspectionMethod,key:K,value:IncomingInspectionMethodPlan[K])=>setPlans(c=>({...c,[method]:{...c[method],[key]:value}}));
 const toggle=(method:IncomingInspectionMethod)=>setSelectedMethods(c=>c.includes(method)?(c.length===1?c:c.filter(x=>x!==method)):[...c,method]);
 const submit=async(e:FormEvent)=>{e.preventDefault(); const total=Number(totalLotQuantity); const responsiblePm=responsiblePms.find(pm=>pm.email===responsiblePmEmail); const methodPlans=selectedMethods.map(m=>plans[m].isFullInspection?{...plans[m],inspectedQuantity:total,aql:"",allowedRejectedQuantity:0}:plans[m]);
  if(!lotName.trim())return setFormError("Agrega el nombre del lote."); if(!Number.isInteger(total)||total<1)return setFormError("La cantidad total del lote debe ser mayor a cero."); if(!responsiblePm)return setFormError("Selecciona al PM responsable.");
  for(const plan of methodPlans){const label=METHOD_OPTIONS.find(x=>x.value===plan.method)?.label; if(plan.isFullInspection)continue; if(!Number.isInteger(plan.inspectedQuantity)||plan.inspectedQuantity<1||plan.inspectedQuantity>total)return setFormError(`Agrega una cantidad por inspeccionar válida para ${label}.`); if(!plan.aql.trim())return setFormError(`Completa el AQL para ${label}.`); if(!Number.isInteger(plan.allowedRejectedQuantity)||plan.allowedRejectedQuantity<0||plan.allowedRejectedQuantity>plan.inspectedQuantity)return setFormError(`Los rechazos permitidos de ${label} deben estar entre cero y su cantidad por inspeccionar.`)}
  try{setFormError("");await onSubmit({lotName:lotName.trim(),totalLotQuantity:total,methodPlans,responsiblePm})}catch(c){setFormError(c instanceof Error?c.message:"No fue posible crear el lote.")}
 };
 return <form onSubmit={submit} className="space-y-6">
  <div className="flex items-start gap-4 rounded-2xl border border-emerald-400/20 bg-emerald-400/[0.06] p-5"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl border border-emerald-400/25 bg-emerald-400/10 text-emerald-300"><PackagePlus size={21}/></div><div><h2 className="font-semibold text-white">Agregar lote de inspección</h2><p className="mt-1 text-sm text-white/55">Selecciona uno o varios métodos y configura el muestreo de cada uno.</p></div></div>
  <div><p className="text-sm font-medium text-white/75">Métodos de inspección</p><div className="mt-2 grid grid-cols-2 gap-2 sm:grid-cols-4">{METHOD_OPTIONS.map(({value,label})=><button key={value} type="button" onClick={()=>toggle(value)} className={`rounded-xl border px-3 py-3 text-sm ${selectedMethods.includes(value)?"border-emerald-400/35 bg-emerald-400/10 text-emerald-100":"border-white/10 text-white/45"}`}>{label}</button>)}</div></div>
  <div className="grid gap-5 sm:grid-cols-3"><label className="text-sm text-white/75 sm:col-span-2">Nombre del lote<input value={lotName} onChange={e=>setLotName(e.target.value)} className="mt-2 min-h-12 w-full rounded-xl border border-white/15 bg-black/25 px-4 text-white"/></label><label className="text-sm text-white/75">Cantidad total del lote<input type="number" min="1" value={totalLotQuantity} onChange={e=>setTotalLotQuantity(e.target.value)} className="mt-2 min-h-12 w-full rounded-xl border border-white/15 bg-black/25 px-4 text-white"/></label></div>
  <div className="space-y-4">{selectedMethods.map((method,index)=>{const plan=plans[method];const label=METHOD_OPTIONS.find(x=>x.value===method)?.label;return <section key={method} className="rounded-2xl border border-white/10 bg-white/[0.025] p-5"><p className="text-xs font-semibold uppercase tracking-wider text-emerald-300">{selectedMethods.length===1?"Plan de inspección":`Método ${index+1}`}</p><h3 className="mt-1 font-semibold text-white">{label}</h3><label className="mt-4 flex cursor-pointer items-start gap-3 rounded-xl border border-emerald-400/20 bg-emerald-400/[0.05] p-4"><input type="checkbox" checked={plan.isFullInspection===true} onChange={e=>update(method,"isFullInspection",e.target.checked)} className="mt-0.5 h-4 w-4 accent-emerald-400"/><span><span className="block text-sm font-medium text-emerald-100">Inspección del 100%</span><span className="mt-1 block text-xs leading-5 text-white/45">Se inspeccionará la cantidad total del lote. No se requiere AQL, tipo, nivel ni rechazos permitidos.</span></span></label>{plan.isFullInspection?<p className="mt-4 rounded-xl border border-white/10 bg-black/15 px-4 py-3 text-sm text-white/55">Cantidad por inspeccionar: <span className="font-medium text-white">{Number(totalLotQuantity)>0?`${totalLotQuantity} piezas (todo el lote)`:"se definirá con la cantidad total del lote"}</span></p>:<div className="mt-4 grid gap-4 sm:grid-cols-5">
   <label className="text-sm text-white/70">Cantidad por inspeccionar<input type="number" min="1" value={plan.inspectedQuantity||""} onChange={e=>update(method,"inspectedQuantity",Number(e.target.value))} className="mt-2 min-h-11 w-full rounded-xl border border-white/10 bg-black/20 px-3 text-white"/></label>
   <label className="text-sm text-white/70">Tipo de inspección<select value={plan.inspectionType} onChange={e=>update(method,"inspectionType",e.target.value as IncomingInspectionType)} className="mt-2 min-h-11 w-full rounded-xl border border-white/10 bg-[#111916] px-3 text-white"><option value="normal">Normal</option><option value="special">Especial</option></select></label>
   <label className="text-sm text-white/70">Nivel<select value={plan.inspectionLevel} onChange={e=>update(method,"inspectionLevel",e.target.value as IncomingInspectionLevel)} className="mt-2 min-h-11 w-full rounded-xl border border-white/10 bg-[#111916] px-3 text-white">{LEVELS.map(l=><option key={l}>{l}</option>)}</select></label>
   <label className="text-sm text-white/70">AQL<input value={plan.aql} onChange={e=>update(method,"aql",e.target.value)} className="mt-2 min-h-11 w-full rounded-xl border border-white/10 bg-black/20 px-3 text-white"/></label>
   <label className="text-sm text-white/70">Rechazos permitidos<input type="number" min="0" value={plan.allowedRejectedQuantity||""} onChange={e=>update(method,"allowedRejectedQuantity",Number(e.target.value))} className="mt-2 min-h-11 w-full rounded-xl border border-white/10 bg-black/20 px-3 text-white"/></label>
  </div>}</section>})}</div>
  <label className="block text-sm text-white/75">PM responsable<select value={responsiblePmEmail} onChange={e=>setResponsiblePmEmail(e.target.value)} disabled={saving||loadingPms} className="mt-2 min-h-12 w-full rounded-xl border border-white/15 bg-[#111916] px-4 text-white"><option value="">{loadingPms?"Cargando responsables...":"Selecciona un responsable"}</option>{responsiblePms.map(pm=><option key={pm.email} value={pm.email}>{pm.name} - {pm.email}</option>)}</select></label>
  {formError&&<p className="rounded-xl border border-red-400/25 bg-red-400/[0.08] px-4 py-3 text-sm text-red-100">{formError}</p>}
  <div className="flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><button type="button" onClick={onCancel} className="rounded-xl border border-white/10 px-5 py-3 text-sm text-white/60">Cancelar</button><button type="submit" disabled={saving} className="inline-flex items-center justify-center gap-2 rounded-xl border border-emerald-400/30 bg-emerald-400/15 px-5 py-3 text-sm font-medium text-emerald-100">{saving&&<LoaderCircle size={16} className="animate-spin"/>}Crear lote</button></div>
 </form>
}
