"use client";
import { useState } from "react";
import { doc, runTransaction } from "firebase/firestore";
import { db } from "@/src/firebase/firebaseConfig";
import { useAuth } from "@/src/Context/AuthContext";
import type { IncomingInspectionContext, IncomingInspectionLot, IncomingLotReport } from "../types";
import { incomingMethodLabel } from "../qmsReportData";
export default function ShiftInspectionChecks({context,lot,reports}:{context:IncomingInspectionContext;lot:IncomingInspectionLot;reports:IncomingLotReport[]}) {
 const {user}=useAuth(); const plans=lot.methodPlans.filter(p=>p.perShift); const [method,setMethod]=useState(plans[0]?.method||"visual");const [shift,setShift]=useState("");const [number,setNumber]=useState("");const [error,setError]=useState("");const [saving,setSaving]=useState(false);
 if(!plans.length)return null;
 const save=async()=>{try{setSaving(true);setError("");const plan=plans.find(p=>p.method===method);const n=Number(number);if(!user||!shift.trim()||!Number.isInteger(n)||n<1||n>Number(plan?.inspectionsPerShift))throw Error("Identifica el turno y el número de inspección válido.");if(reports.some(r=>r.inspectionMethod===method&&r.shiftIdentifier===shift.trim()&&r.shiftInspectionNumber===n))throw Error("Esta inspección ya tiene un rechazo por SPEC.");await runTransaction(db,async t=>{const ref=doc(db,"inspection_incoming_lots",context.scopeKey,"lots",lot.id);const snap=await t.get(ref);const data=snap.data();if(data?.status!=="in_progress")throw Error("El lote está finalizado.");const checks=data.shiftChecks||[];if(checks.some((c:{method:string;shiftIdentifier:string;inspectionNumber:number})=>c.method===method&&c.shiftIdentifier===shift.trim()&&c.inspectionNumber===n))throw Error("Esta inspección ya se registró.");t.update(ref,{shiftChecks:[...checks,{method,shiftIdentifier:shift.trim(),inspectionNumber:n,result:"pass",createdBy:user!.displayName||user!.email||"Usuario",createdAt:new Date().toISOString()}]});});setNumber("");}catch(e){setError(e instanceof Error?e.message:"No se pudo registrar.");}finally{setSaving(false)}};
 return <section className="rounded-xl border border-white/10 p-4"><h3 className="font-medium text-white">Inspecciones por turno</h3><p className="mt-2 text-xs text-white/50">Registra aquí las inspecciones que pasaron. Si una no pasa por SPEC, registra el rechazo con el mismo turno y número de inspección.</p>{lot.status==="in_progress"&&<div className="mt-3 grid gap-2 sm:grid-cols-4"><select value={method} onChange={e=>setMethod(e.target.value as typeof method)} className="rounded bg-[#111916] p-2 text-white">{plans.map(p=><option key={p.method} value={p.method}>{incomingMethodLabel(p.method)}</option>)}</select><input value={shift} onChange={e=>setShift(e.target.value)} placeholder="Día / identificación de turno" className="rounded bg-black/20 p-2 text-white"/><input type="number" min="1" value={number} onChange={e=>setNumber(e.target.value)} placeholder="# de inspección" className="rounded bg-black/20 p-2 text-white"/><button type="button" disabled={saving} onClick={save} className="rounded bg-emerald-500/20 p-2 text-emerald-100">Registrar: pasó</button></div>}{error&&<p className="mt-2 text-sm text-red-200">{error}</p>}<div className="mt-3 space-y-1 text-xs text-white/60">{(lot.shiftChecks||[]).map((c,i)=><p key={i}>{incomingMethodLabel(c.method)} · {c.shiftIdentifier} · #{c.inspectionNumber}: pasó</p>)}{reports.filter(r=>r.shiftIdentifier).map(r=><p key={r.id} className="text-red-200">{incomingMethodLabel(r.inspectionMethod)} · {r.shiftIdentifier} · #{r.shiftInspectionNumber}: no pasó · {r.title}</p>)}</div></section>;
}
