"use client";
import { useInventorySite } from "@/app/components/inventario/InventoryProvider";
import { inventoryHref } from "@/lib/inventario/sites";
import Link from "next/link";
import { Boxes, ArrowRight } from "lucide-react";
import type { InventoryComponent } from "@/lib/inventario/types";
import { TYPES } from "@/lib/inventario/catalogs";
export default function InventoryTable({ components, warehouse, loading }: { components: InventoryComponent[]; warehouse: string; loading: boolean }) {
  const { site } = useInventorySite();
  const total = (c: InventoryComponent) => Number(c.lots.reduce((sum, l) => sum + (warehouse ? l.stock[warehouse] || 0 : Object.values(l.stock).reduce((a, b) => a + b, 0)), 0).toFixed(6));
  const lots = (c: InventoryComponent) => c.lots.filter(l => !warehouse || (l.stock[warehouse] || 0) > 0).length;
  return <section className="relative overflow-hidden rounded-2xl border border-white/10 bg-white/[0.035] backdrop-blur-sm ring-1 ring-white/5 sm:rounded-3xl sm:backdrop-blur-2xl sm:shadow-[0_30px_120px_-80px_rgba(0,0,0,0.95)]"><div className="pointer-events-none absolute inset-x-0 top-0 h-24 bg-gradient-to-b from-emerald-500/10 to-transparent" />
    {loading || !components.length ? <div className="relative flex flex-col items-center gap-3 px-5 py-14 text-center"><Boxes size={28} className="text-white/25" /><p className="text-sm font-medium text-white/75">{loading ? "Cargando inventario…" : "Sin artículos para esta selección"}</p>{!loading && <p className="max-w-sm text-xs leading-relaxed text-white/40">Crea un artículo y registra su primer lote, o cambia los filtros para consultar otras existencias.</p>}</div> : <>
      <div className="relative divide-y divide-white/10 lg:hidden">{components.map(c => <Link key={c.id} href={inventoryHref(`/inventario/components/${c.id}`, site)} className="flex items-center justify-between gap-4 px-4 py-4 transition hover:bg-white/[0.03]"><div className="min-w-0"><p className="break-words text-sm font-semibold text-white/90">{c.code} · {c.name}</p><p className="mt-1 text-xs text-white/45">{c.project || "General / MTS"} · {lots(c)} lotes</p></div><div className="shrink-0 text-right"><p className="text-sm tabular-nums text-emerald-100">{total(c)} {c.unit}</p><p className="mt-1 text-xs text-white/35">{TYPES[c.type]}</p></div></Link>)}</div>
      <div className="relative hidden overflow-x-auto lg:block"><table className="w-full min-w-[850px] text-sm"><thead className="bg-white/[0.02]"><tr className="text-left text-xs tracking-wide text-white/55">{["Artículo", "Proyecto", "Tipo", "Cantidad", "Lotes", "Detalles"].map(h => <th key={h} className="px-4 py-3 font-semibold">{h}</th>)}</tr></thead><tbody className="divide-y divide-white/10">{components.map(c => <tr key={c.id} className="align-top transition hover:bg-emerald-500/[0.04]"><td className="px-4 py-3"><p className="font-medium text-white/90">{c.name}</p><p className="mt-1 text-[11px] text-white/40">{c.code}</p></td><td className="px-4 py-3 text-white/75">{c.project || "General / MTS"}</td><td className="px-4 py-3"><span className="inline-flex rounded-full border border-white/10 bg-white/[0.04] px-2.5 py-1 text-xs text-white/65">{c.type} · {TYPES[c.type]}</span></td><td className="px-4 py-3 tabular-nums text-white/85">{total(c)} {c.unit}</td><td className="px-4 py-3 text-white/65">{lots(c)}</td><td className="px-4 py-3"><Link href={inventoryHref(`/inventario/components/${c.id}`, site)} className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-white/[0.05] px-3 py-2 text-xs text-white/80 transition hover:bg-white/[0.09]">Ver detalles<ArrowRight size={13} /></Link></td></tr>)}</tbody></table></div>
    </>}<div className="relative border-t border-white/10 px-4 py-3 text-xs text-white/45">{components.length} artículos · {warehouse ? "Existencias del almacén seleccionado" : "Existencias en todos los almacenes"}</div>
  </section>;
}
