"use client";
import { useState } from "react";
import { auth } from "@/src/firebase/firebaseConfig";
import type { Voucher } from "@/lib/inventario/types";
import { locationName } from "@/lib/inventario/catalogs";
import { buttonClass } from "./InventoryShell";
export default function MaterialVoucher({ voucher: v }: { voucher: Voucher }) {
  const [busy,setBusy]=useState(false),[error,setError]=useState("");
  async function download(){setBusy(true);setError("");try{if(!auth.currentUser)throw new Error("Inicia sesión.");const r=await fetch(`/api/inventario/vales/${encodeURIComponent(v.id)}/docx?site=${v.site||"B1"}`,{cache:"no-store",headers:{Authorization:`Bearer ${await auth.currentUser.getIdToken()}`}});if(!r.ok){const d=await r.json();throw new Error(d.error||"No se pudo descargar.");}const url=URL.createObjectURL(await r.blob());const a=document.createElement("a");a.href=url;a.download=`Vale-${v.site||"B1"}-${v.id}.docx`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(e instanceof Error?e.message:"Error.");}finally{setBusy(false);}}
  const stamp = new Date(v.createdAt).toLocaleString("es-MX", { timeZone: "America/Mexico_City" });
  return <><div className="print-hide space-y-2"><button onClick={download} disabled={busy} className={buttonClass}>{busy?"Generando…":"Descargar vale oficial Word"}</button><p className="text-xs text-white/50">Abre el documento oficial en Word para imprimirlo o guardarlo como PDF.</p>{error&&<p role="alert" className="text-sm text-red-300">{error}</p>}</div><article className="voucher space-y-5 rounded-xl bg-white p-6 text-black">
    <div className="flex justify-between gap-4 border-b pb-4"><h1 className="text-2xl font-bold">BIOANA · Vale de Material</h1><p className="text-right text-xs">FRM.019.05C<br />Folio: {v.id}</p></div>
    <div className="grid grid-cols-2 gap-3 text-sm"><p><b>Almacén:</b> {v.site || "B1"}</p><p><b>Fecha:</b> {stamp}</p><p><b>Tipo:</b> {v.kind === "traslado" ? "Salida / entrada por traslado" : v.kind === "entrada" ? "Entrada" : "Salida"}</p><p><b>Origen:</b> {locationName(v.origin)}</p><p><b>Destino:</b> {locationName(v.destination)}</p><p><b>Proceso / proyecto:</b> {v.project || [...new Set(v.lines.map(l => l.project).filter(Boolean))].join(", ") || "N/A"}</p><p><b>Registrado por:</b> {v.actor}</p></div>
    <div className="overflow-x-auto"><table className="w-full border-collapse text-xs"><thead><tr>{["Artículo", "Unidad", "Cantidad", "Lote", "Caducidad / reanálisis", "Comentarios"].map(h => <th key={h} className="border border-gray-400 p-2 text-left">{h}</th>)}</tr></thead><tbody>{v.lines.map((l, i) => <tr key={i}><td className="border border-gray-400 p-2">{l.code}<br />{l.name}</td><td className="border border-gray-400 p-2">{l.unit}</td><td className="border border-gray-400 p-2">{l.quantity}</td><td className="border border-gray-400 p-2">{l.lot}</td><td className="border border-gray-400 p-2">{l.expiry || "N/A"}</td><td className="border border-gray-400 p-2">{l.comments}</td></tr>)}</tbody></table></div>
    <p className="whitespace-pre-wrap text-sm"><b>Comentarios generales:</b> {v.notes || "N/A"}</p>
    <div className="grid grid-cols-3 gap-6 pt-12 text-xs">{[["Quien solicita", v.requestedBy], ["Quien recibe (si aplica)", v.receivedBy], ["Quien surte / registra", v.actor]].map(([label, name]) => <div key={label} className="border-t border-black pt-2"><p>{label}</p><p>{name || "________________"}</p><p className="mt-3">Firma: __________________</p></div>)}</div>
  </article><style>{`@media print { @page { size: A4; margin: 12mm; } header, footer, nav, .print-hide { display:none !important; } body { background:white !important; color:black !important; } body::before, body::after {display:none !important} main {padding:0 !important; margin:0 !important; max-width:none !important} .voucher {padding:0 !important; background:white !important; color:black !important;} .voucher table {font-size:10px} .voucher thead {display:table-header-group} .voucher tr {break-inside:avoid} .voucher td {overflow-wrap:anywhere} }`}</style></>;
}
